services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - HTTP_PROXY={HTTP_PROXY}
      - http_proxy={HTTP_PROXY}
      - HTTPS_PROXY={HTTP_PROXY}
      - https_proxy={HTTP_PROXY}
    ports:
      - "${PORT}:${PORT}"
    command: npm run start
