version: '3.9'
services:
  instant-mock-e2e-record:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instant-mock-e2e-record
    environment:
      PORT: "${RECORD_PORT}"
      PLAY_PORT: "${PLAY_PORT}"
      RECORD_PORT: "${RECORD_PORT}"
      NODE_ENV: "e2e-record"
      APOLLO_API_KEY: "${APOLLO_API_KEY}"
      HOST: 0.0.0.0
    ports:
      - "${RECORD_PORT}:${RECORD_PORT}"
    networks:
      - instant-mock-network
  instant-mock-e2e-play:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instant-mock-e2e-play
    environment:
      PORT: "${PLAY_PORT}"
      PLAY_PORT: "${PLAY_PORT}"
      NODE_ENV: "e2e-play"
      APOLLO_API_KEY: "${APOLLO_API_KEY}"
      USE_LOCAL_SCHEMA: "true"
    ports:
      - "${PLAY_PORT}:${PLAY_PORT}"
    volumes:
      - "./test/e2e/fixtures/${FIXTURE_TIMESTAMP}:/app/backend/data/"
    networks:
      - instant-mock-network
  instant-mock-e2e-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instant-mock-e2e-test
    environment:
      PORT: "${TEST_PORT}"
      PLAY_PORT: "${PLAY_PORT}"
      NODE_ENV: "e2e-test"
    ports:
      - "${TEST_PORT}:${TEST_PORT}"
    networks:
      - instant-mock-network
networks:
  instant-mock-network:
    driver: bridge
