version: '3.9'
services:
  instant-mock-e2e-record:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instant-mock-e2e-record
    environment:
      PORT: 3035
      NODE_ENV: "e2e-record"
      APOLLO_API_KEY: "${APOLLO_API_KEY}"
    ports:
      - "3035:3035"
    volumes:
      - "./test/e2e/fixtures/apollo-platform-api/${FIXTURE_TIMESTAMP}/instant-mock.db:/app/data/instant-mock-record.db"
  instant-mock-e2e-play:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instant-mock-e2e-play
    environment:
      PORT: 3034
      NODE_ENV: "e2e-play"
    ports:
      - "3034:3034"
    volumes:
      - "./test/e2e/fixtures/apollo-platform-api/${FIXTURE_TIMESTAMP}/instant-mock.db:/app/data/instant-mock-record.db"
  instant-mock-e2e-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instant-mock-e2e-test
    environment:
      PORT: 3036
      NODE_ENV: "e2e-test"
    ports:
      - "3036:3036"
