services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HTTP_PROXY={HTTP_PROXY}
      - http_proxy={HTTP_PROXY}
      - HTTPS_PROXY={HTTP_PROXY}
      - https_proxy={HTTP_PROXY}
    ports:
      - "3001:3001"
    command: npm run start
