replicaCount: 1
image:
  repository: xolvio/instant-mock
  tag: 1.0.0-beta.4.6
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: istio
  annotations:
    kubernetes.io/ingress.class: istio
  hosts:
    - host: instant-mock.example.com
      paths:
        - path: /
          pathType: Prefix
env:
  - name: NODE_ENV
    value: production
  - name: BACKEND_URL
    value: instant-mock.example.com
  - name: PORT
    value: '80'
  - name: BACKEND_PROTO
    value: https
  - name: MIKRO_ORM_DRIVER
    value: postgres
resources: {}
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

postgres:
  image:
    repository: postgres
    tag: "15"
    pullPolicy: Always
  database: mydb
  username: myuser
  password: mypassword
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
  service:
    port: 5432