replicaCount: 1
image:
  repository: xolvio/instant-mock
  tag: 1.0.0-beta.2
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
resources: {}
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
